### ISSUE TITLE
Use proper way of rxjs imports

### ISSUE THREAD

**Issue by pburgmer** [valor-software/ng2-tree#172]
Hi,

First of all: Thanks for this cool library.

We have some trouble building a bigger application with the Angular CLI. Digging deeper I saw you import Observables like this: ```import { Observable } from 'rxjs/Rx';```. This kind of import statements leads to a bigger file size. Please see https://christianliebel.com/2017/07/import-rxjs-correctly/ for more details.

Could you please update your import statements to ```import { Observable } from 'rxjs/Observable';``` and add the operators manually.

Thanks

**Comment by rychkog** [comment]
@pburgmer Agree, this is a good point. Will update the lib during this week.

**Comment by pburgmer** [comment]
Thanks

**Comment by Myrmex** [comment]
Maybe this comment can be useful: I'm finding that in my Angular CLI app using ng2tree works fine but only when compiling in prod mode (with or without `--aot`); when I compile for production (`--prod`), I get an error which seems related to this style of rxjs import. Hope making that update will solve this, too.
Here is the build error:

```text
ERROR in ./node_modules/rxjs/_esm5/observable/BoundNodeCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (D:\Projects\Core20\Spa\chironweb\node_modules\typescript\lib\typescript.js:9341:18)
    at assignContextualParameterTypes (D:\Projects\Core20\Spa\chironweb\node_modules\typescript\lib\typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (D:\Projects\Core20\Spa\chironweb\node_modules\typescript\lib\typescript.js:41948:29)
    at checkExpressionWorker (D:\Projects\Core20\Spa\chironweb\node_modules\typescript\lib\typescript.js:42959:28)
    at checkExpression (D:\Projects\Core20\Spa\chironweb\node_modules\typescript\lib\typescript.js:42898:42)
    at checkExpressionCached (D:\Projects\Core20\Spa\chironweb\node_modules\typescript\lib\typescript.js:42779:38)
    at checkReturnStatement (D:\Projects\Core20\Spa\chironweb\node_modules\typescript\lib\typescript.js:45418:54)
    at checkSourceElement (D:\Projects\Core20\Spa\chironweb\node_modules\typescript\lib\typescript.js:46763:28)
    at Object.forEach (D:\Projects\Core20\Spa\chironweb\node_modules\typescript\lib\typescript.js:1506:30)
    at checkBlock (D:\Projects\Core20\Spa\chironweb\node_modules\typescript\lib\typescript.js:44563:16)
    at checkSourceElement (D:\Projects\Core20\Spa\chironweb\node_modules\typescript\lib\typescript.js:46742:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (D:\Projects\Core20\Spa\chironweb\node_modules\typescript\lib\typescript.js:41990:21)
    at checkDeferredNodes (D:\Projects\Core20\Spa\chironweb\node_modules\typescript\lib\typescript.js:46828:25)
    at checkSourceFileWorker (D:\Projects\Core20\Spa\chironweb\node_modules\typescript\lib\typescript.js:46863:17)
    at checkSourceFile (D:\Projects\Core20\Spa\chironweb\node_modules\typescript\lib\typescript.js:46842:13)
    at Object.forEach (D:\Projects\Core20\Spa\chironweb\node_modules\typescript\lib\typescript.js:1506:30)
 @ ./node_modules/rxjs/_esm5/observable/bindNodeCallback.js 2:0-76
 @ ./node_modules/rxjs/_esm5/add/observable/bindNodeCallback.js
 @ ./node_modules/rxjs/_esm5/Rx.js
 @ ./node_modules/ng2-tree/src/menu/node-menu.service.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts
 ```

**Comment by pburgmer** [comment]
I have the same error.

**Comment by avadhootha** [comment]
I updated the same issue over angular cli project as well - https://github.com/angular/angular-cli/issues/2281

Upgrading the typescript version to 2.6 also resolves the issue. But I think this library eventually have to replace the statements `import { Observable } from 'rxjs/Rx';` as @pburgmer  said.
