### ISSUE TITLE
Error in TypeError: Cannot ready property 'version' of null

### ISSUE THREAD

**Issue by avadhootha** [valor-software/ng2-tree#175]
I updated ng2-tree version to `'2.0.0-rc.3'` in my project and tried `ng build --prod --build-optimizer` which threw this error.
Error:
```
 10% building modules 3/3 modules 0 activeFailed to read JSON file /home/project/node_modules/ng2-tree/src/rxjs-imports.metadata.json
Date: 2017-11-25T07:44:00.337Z                                                       
Hash: 0717c0287e377b6bbfb2
Time: 4122ms
chunk {0} styles.3e5ed126c359806108c5.bundle.css (styles) 100 kB [initial] [rendered]
chunk {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 86 bytes [initial] [rendered]
chunk {2} main.e402deade8b026b7d50e.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.22b7623ed7c5ac6f9a35.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in TypeError: Cannot read property 'version' of null
    at readMetadataFile ( /home/project/ngmpui/node_modules/@angular/compiler-cli/src/transformers/metadata_reader.js:66:28)
    at Object.readMetadata  /home/project/ngmpui/node_modules/@angular/compiler-cli/src/transformers/metadata_reader.js:35:25)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getMetadataFor ( /home/project/ngmpui/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:413:34)
    at StaticSymbolResolver.getModuleMetadata ( /home/project/node_modules/@angular/compiler/bundles/compiler.umd.js:31804:62)
    at StaticSymbolResolver.hasDecorators ( /home/project/node_modules/@angular/compiler/bundles/compiler.umd.js:31531:46)
    at analyzeFile ( /home/project/node_modules/@angular/compiler/bundles/compiler.umd.js:30078:63)
    at AotCompiler._analyzeFile ( /home/project/node_modules/@angular/compiler/bundles/compiler.umd.js:29306:17)
    at AotCompiler.findGeneratedFileNames ( /home/project/node_modules/@angular/compiler/bundles/compiler.umd.js:29322:42)
    at Object.findGeneratedFileNames ( /home/project/node_modules/@angular/compiler-cli/src/transformers/program.js:392:82)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getSourceFile ( /home/project/node_modules/@angular/compiler-cli/src/transformers/compiler_host.js:325:55)
    at findSourceFile ( /home/project/node_modules/typescript/lib/typescript.js:70246:29)
    at processImportedModules ( /home/project/node_modules/typescript/lib/typescript.js:70393:25)
    at findSourceFile ( /home/project/node_modules/typescript/lib/typescript.js:70274:17)
    at processImportedModules ( /home/project/node_modules/typescript/lib/typescript.js:70393:25)
    at findSourceFile ( /home/project/node_modules/typescript/lib/typescript.js:70274:17)
    at args  /home/project/node_modules/typescript/lib/typescript.js:70200:85)
```

I see the file rxjs-imports.metadata.json contains `[null]`. Is this something to do this error?

**Comment by rychkog** [comment]
@avadhootha Already looking at this - seems like angular compiler doesn't like files like this

**Comment by rychkog** [comment]
I've checked prod using  `build --prod --build-optimizer` and it worked.

@avadhootha Please, let me know whether that helped (ng2-tree 2.0.0-rc.4)

**Comment by avadhootha** [comment]
It works fine now with ng2-tree 2.0.0-rc.4. Thanks for the quick response.
